//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  /** Internal type. DO NOT USE DIRECTLY. */
type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
/** Internal type. DO NOT USE DIRECTLY. */
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Folder;

export type HomeHero = {
  __typename?: 'HomeHero';
  eyebrow?: Maybe<Scalars['String']['output']>;
  headline?: Maybe<Scalars['String']['output']>;
  headlineAccent?: Maybe<Scalars['String']['output']>;
  sub?: Maybe<Scalars['String']['output']>;
  ctaPrimary?: Maybe<Scalars['String']['output']>;
  ctaSecondary?: Maybe<Scalars['String']['output']>;
};

export type HomeProblem = {
  __typename?: 'HomeProblem';
  eyebrow?: Maybe<Scalars['String']['output']>;
  lead?: Maybe<Scalars['String']['output']>;
};

export type HomeStats = {
  __typename?: 'HomeStats';
  num?: Maybe<Scalars['String']['output']>;
  label?: Maybe<Scalars['String']['output']>;
  note?: Maybe<Scalars['String']['output']>;
};

export type HomeProductCards = {
  __typename?: 'HomeProductCards';
  tag?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomeProduct = {
  __typename?: 'HomeProduct';
  eyebrow?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  cards?: Maybe<Array<Maybe<HomeProductCards>>>;
};

export type HomeApproachPoints = {
  __typename?: 'HomeApproachPoints';
  kicker?: Maybe<Scalars['String']['output']>;
  title?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['String']['output']>;
};

export type HomeApproach = {
  __typename?: 'HomeApproach';
  eyebrow?: Maybe<Scalars['String']['output']>;
  leadStart?: Maybe<Scalars['String']['output']>;
  leadEmphasis?: Maybe<Scalars['String']['output']>;
  leadEnd?: Maybe<Scalars['String']['output']>;
  points?: Maybe<Array<Maybe<HomeApproachPoints>>>;
};

export type HomeContact = {
  __typename?: 'HomeContact';
  eyebrow?: Maybe<Scalars['String']['output']>;
  heading?: Maybe<Scalars['String']['output']>;
  sub?: Maybe<Scalars['String']['output']>;
};

export type Home = Node & Document & {
  __typename?: 'Home';
  hero?: Maybe<HomeHero>;
  problem?: Maybe<HomeProblem>;
  stats?: Maybe<Array<Maybe<HomeStats>>>;
  product?: Maybe<HomeProduct>;
  approach?: Maybe<HomeApproach>;
  contact?: Maybe<HomeContact>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomeHeroFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  headline?: InputMaybe<StringFilter>;
  headlineAccent?: InputMaybe<StringFilter>;
  sub?: InputMaybe<StringFilter>;
  ctaPrimary?: InputMaybe<StringFilter>;
  ctaSecondary?: InputMaybe<StringFilter>;
};

export type HomeProblemFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  lead?: InputMaybe<StringFilter>;
};

export type HomeStatsFilter = {
  num?: InputMaybe<StringFilter>;
  label?: InputMaybe<StringFilter>;
  note?: InputMaybe<StringFilter>;
};

export type HomeProductCardsFilter = {
  tag?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomeProductFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  cards?: InputMaybe<HomeProductCardsFilter>;
};

export type HomeApproachPointsFilter = {
  kicker?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  body?: InputMaybe<StringFilter>;
};

export type HomeApproachFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  leadStart?: InputMaybe<StringFilter>;
  leadEmphasis?: InputMaybe<StringFilter>;
  leadEnd?: InputMaybe<StringFilter>;
  points?: InputMaybe<HomeApproachPointsFilter>;
};

export type HomeContactFilter = {
  eyebrow?: InputMaybe<StringFilter>;
  heading?: InputMaybe<StringFilter>;
  sub?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  hero?: InputMaybe<HomeHeroFilter>;
  problem?: InputMaybe<HomeProblemFilter>;
  stats?: InputMaybe<HomeStatsFilter>;
  product?: InputMaybe<HomeProductFilter>;
  approach?: InputMaybe<HomeApproachFilter>;
  contact?: InputMaybe<HomeContactFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
};

export type HomeHeroMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  headline?: InputMaybe<Scalars['String']['input']>;
  headlineAccent?: InputMaybe<Scalars['String']['input']>;
  sub?: InputMaybe<Scalars['String']['input']>;
  ctaPrimary?: InputMaybe<Scalars['String']['input']>;
  ctaSecondary?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProblemMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  lead?: InputMaybe<Scalars['String']['input']>;
};

export type HomeStatsMutation = {
  num?: InputMaybe<Scalars['String']['input']>;
  label?: InputMaybe<Scalars['String']['input']>;
  note?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProductCardsMutation = {
  tag?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomeProductMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  cards?: InputMaybe<Array<InputMaybe<HomeProductCardsMutation>>>;
};

export type HomeApproachPointsMutation = {
  kicker?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['String']['input']>;
};

export type HomeApproachMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  leadStart?: InputMaybe<Scalars['String']['input']>;
  leadEmphasis?: InputMaybe<Scalars['String']['input']>;
  leadEnd?: InputMaybe<Scalars['String']['input']>;
  points?: InputMaybe<Array<InputMaybe<HomeApproachPointsMutation>>>;
};

export type HomeContactMutation = {
  eyebrow?: InputMaybe<Scalars['String']['input']>;
  heading?: InputMaybe<Scalars['String']['input']>;
  sub?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  hero?: InputMaybe<HomeHeroMutation>;
  problem?: InputMaybe<HomeProblemMutation>;
  stats?: InputMaybe<Array<InputMaybe<HomeStatsMutation>>>;
  product?: InputMaybe<HomeProductMutation>;
  approach?: InputMaybe<HomeApproachMutation>;
  contact?: InputMaybe<HomeContactMutation>;
};

export type StringFilter = {
  startsWith?: string | null | undefined;
  eq?: string | null | undefined;
  exists?: boolean | null | undefined;
  in?: Array<string | null | undefined> | null | undefined;
};

export type HomeHeroFilter = {
  eyebrow?: StringFilter | null | undefined;
  headline?: StringFilter | null | undefined;
  headlineAccent?: StringFilter | null | undefined;
  sub?: StringFilter | null | undefined;
  ctaPrimary?: StringFilter | null | undefined;
  ctaSecondary?: StringFilter | null | undefined;
};

export type HomeProblemFilter = {
  eyebrow?: StringFilter | null | undefined;
  lead?: StringFilter | null | undefined;
};

export type HomeStatsFilter = {
  num?: StringFilter | null | undefined;
  label?: StringFilter | null | undefined;
  note?: StringFilter | null | undefined;
};

export type HomeProductCardsFilter = {
  tag?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
};

export type HomeProductFilter = {
  eyebrow?: StringFilter | null | undefined;
  heading?: StringFilter | null | undefined;
  cards?: HomeProductCardsFilter | null | undefined;
};

export type HomeApproachPointsFilter = {
  kicker?: StringFilter | null | undefined;
  title?: StringFilter | null | undefined;
  body?: StringFilter | null | undefined;
};

export type HomeApproachFilter = {
  eyebrow?: StringFilter | null | undefined;
  leadStart?: StringFilter | null | undefined;
  leadEmphasis?: StringFilter | null | undefined;
  leadEnd?: StringFilter | null | undefined;
  points?: HomeApproachPointsFilter | null | undefined;
};

export type HomeContactFilter = {
  eyebrow?: StringFilter | null | undefined;
  heading?: StringFilter | null | undefined;
  sub?: StringFilter | null | undefined;
};

export type HomeFilter = {
  hero?: HomeHeroFilter | null | undefined;
  problem?: HomeProblemFilter | null | undefined;
  stats?: HomeStatsFilter | null | undefined;
  product?: HomeProductFilter | null | undefined;
  approach?: HomeApproachFilter | null | undefined;
  contact?: HomeContactFilter | null | undefined;
};

export type HomePartsFragment = { __typename: 'Home', hero: { __typename: 'HomeHero', eyebrow: string | null, headline: string | null, headlineAccent: string | null, sub: string | null, ctaPrimary: string | null, ctaSecondary: string | null } | null, problem: { __typename: 'HomeProblem', eyebrow: string | null, lead: string | null } | null, stats: Array<{ __typename: 'HomeStats', num: string | null, label: string | null, note: string | null } | null> | null, product: { __typename: 'HomeProduct', eyebrow: string | null, heading: string | null, cards: Array<{ __typename: 'HomeProductCards', tag: string | null, title: string | null, body: string | null } | null> | null } | null, approach: { __typename: 'HomeApproach', eyebrow: string | null, leadStart: string | null, leadEmphasis: string | null, leadEnd: string | null, points: Array<{ __typename: 'HomeApproachPoints', kicker: string | null, title: string | null, body: string | null } | null> | null } | null, contact: { __typename: 'HomeContact', eyebrow: string | null, heading: string | null, sub: string | null } | null };

export type HomeQueryVariables = Exact<{
  relativePath: string;
}>;


export type HomeQuery = { home: { __typename: 'Home', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'HomeHero', eyebrow: string | null, headline: string | null, headlineAccent: string | null, sub: string | null, ctaPrimary: string | null, ctaSecondary: string | null } | null, problem: { __typename: 'HomeProblem', eyebrow: string | null, lead: string | null } | null, stats: Array<{ __typename: 'HomeStats', num: string | null, label: string | null, note: string | null } | null> | null, product: { __typename: 'HomeProduct', eyebrow: string | null, heading: string | null, cards: Array<{ __typename: 'HomeProductCards', tag: string | null, title: string | null, body: string | null } | null> | null } | null, approach: { __typename: 'HomeApproach', eyebrow: string | null, leadStart: string | null, leadEmphasis: string | null, leadEnd: string | null, points: Array<{ __typename: 'HomeApproachPoints', kicker: string | null, title: string | null, body: string | null } | null> | null } | null, contact: { __typename: 'HomeContact', eyebrow: string | null, heading: string | null, sub: string | null } | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: string | null | undefined;
  after?: string | null | undefined;
  first?: number | null | undefined;
  last?: number | null | undefined;
  sort?: string | null | undefined;
  filter?: HomeFilter | null | undefined;
}>;


export type HomeConnectionQuery = { homeConnection: { totalCount: number, pageInfo: { hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges: Array<{ cursor: string, node: { __typename: 'Home', id: string, _sys: { filename: string, basename: string, hasReferences: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, hero: { __typename: 'HomeHero', eyebrow: string | null, headline: string | null, headlineAccent: string | null, sub: string | null, ctaPrimary: string | null, ctaSecondary: string | null } | null, problem: { __typename: 'HomeProblem', eyebrow: string | null, lead: string | null } | null, stats: Array<{ __typename: 'HomeStats', num: string | null, label: string | null, note: string | null } | null> | null, product: { __typename: 'HomeProduct', eyebrow: string | null, heading: string | null, cards: Array<{ __typename: 'HomeProductCards', tag: string | null, title: string | null, body: string | null } | null> | null } | null, approach: { __typename: 'HomeApproach', eyebrow: string | null, leadStart: string | null, leadEmphasis: string | null, leadEnd: string | null, points: Array<{ __typename: 'HomeApproachPoints', kicker: string | null, title: string | null, body: string | null } | null> | null } | null, contact: { __typename: 'HomeContact', eyebrow: string | null, heading: string | null, sub: string | null } | null } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  hero {
    __typename
    eyebrow
    headline
    headlineAccent
    sub
    ctaPrimary
    ctaSecondary
  }
  problem {
    __typename
    eyebrow
    lead
  }
  stats {
    __typename
    num
    label
    note
  }
  product {
    __typename
    eyebrow
    heading
    cards {
      __typename
      tag
      title
      body
    }
  }
  approach {
    __typename
    eyebrow
    leadStart
    leadEmphasis
    leadEnd
    points {
      __typename
      kicker
      title
      body
    }
  }
  contact {
    __typename
    eyebrow
    heading
    sub
  }
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

export type { Exact };

  